### ISSUE TITLE
Project roadmap

### ISSUE THREAD

**Issue by dmittrey** [Vakzu/musical-wars-frontend#1]
- [x] Добавить всплывающую подсказку на иконку эффекта
- [x] Добавить баланс
- [x] Закинуть lobbyId в контекс и localstorage
- [x] Создать API для запроса купленных эффектов
- [x] Создать API для запроса песен героя
- [x] Добавить функционал отправки готовности(с готовностью отправлять 3 выбора)
- [x] Сохранять текущую страницу в localstorage
- [x] Поменять расположение провайдера сокета(сделать активацию сокета только дла авторизированных страниц)
- [x] Реализовать хэндлер для startFightCallback
- [x] Изменить нейминг ручек брокеров(добавить префикс /ws/)
- [x] Добавить анимацию боя
- [x] Добавить кнопку выхода в лобби из поля боя
- [x] Добавить Popup входа в лобби
- [ ] #12
